### ISSUE TITLE
différence entre Viesco et Schoollife (=vie scolaire) ?

### ISSUE THREAD

**Issue by azgaresncf** [PapillonApp/Papillon-ED-Core#3]
Voir getVieSco et Schoollife m'a particulièrement intrigué. J'ai donc testé manuellement les deux endpoints.
Celui de schoollife marche parfaitement, celui de Viesco me log mon IP.
![image](https://github.com/PapillonApp/Papillon-ED-Core/assets/50982832/1ba5d7c8-393b-41b2-aaac-bdbaa12fbb28)

**Comment by LeMaitre4523** [comment]
C'est effectivement la même utilité, pourquoi je l'ai mit deux fois je sais pas mdr, c'est exactement la même requête, la seul diff que je vois c'est le /Eleves/ et /E/

**Comment by azgaresncf** [comment]
Tkt mdrr ☠️
Je vais faire une PR

**Comment by LeMaitre4523** [comment]
Supprime bien ce qui a dans session aussi stp

**Comment by azgaresncf** [comment]
Pas de souci !👌

**Comment by azgaresncf** [comment]
c'est fait
